### ISSUE TITLE
Question regarding TPS service limit.

### ISSUE THREAD

**Issue by hcalsos** [awslabs/amazon-sqs-java-temporary-queues-client#19] opened 2019-10-17 11:12 UTC
Hello.

We have implemented this and during testing we are seeing some errors in the logs.
 
`Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: Request is throttled. (Service: AmazonSQS; Status Code: 403; Error Code: RequestThrottled; Request ID: c8096cbe-1be5-5b2e-8a18-3a9c5fe245d8)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2235)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2202)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2191)
at com.amazonaws.services.sqs.AmazonSQSClient.executeTagQueue(AmazonSQSClient.java:2043)
at com.amazonaws.services.sqs.AmazonSQSClient.tagQueue(AmazonSQSClient.java:2015)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.tagQueue(AbstractAmazonSQSClientWrapper.java:195)
at com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient.lambda$tagQueue$13(AmazonSQSVirtualQueuesClient.java:235)` 

We suspect this is related to the service limit on our account (which is initially set to 5 TPS).
Do you have any recommendation as to which is a good limit to request when submitting a request for service limit increase ?

**Comment by robin-aws** [comment] 2019-10-17 17:43
Hi there! Most of the usage of TagQueue in the library is for heartbeating to keep queues from appearing idle, so it's very likely this is harmless. I'd prefer to improve the library to handle this automatically rather than expect users to increase their limits.

Can you provide the complete stack trace so I can confirm? It's likely there just needs to be a bit more intelligent handling of TagQueue throttling on one of the code paths.

Could you also describe what your testing TPS looks like?

**Comment by hcalsos** [comment] 2019-10-18 08:06
Hello. Thanks for the quick reply.

We are using the default values when building the request/response-clients, using two requesters and one responder. The documentation on aws states that the queue-tag limit is default 5 TPS.
The message queue is configured as a fifo queue.

I have done some more digging into the issue we encountered, and it made me uncertain about whether the root cause is related to the TPS service limit at all. Further examination of the error messages led me to the discovery that our requestors IAM role was missing the sqs:ListQueues, and might be the reason we encountered the throttling issue. It looks like this might be the root cause for being throttled. We added the correct permission to our requestors task role, and today we are not experiencing the same issue. I have included a sample of stacktraces: 

`Oct 17, 2019 7:45:48 AM com.amazonaws.services.sqs.util.SQSQueueUtils lambda$static$0
SEVERE: Unexpected exception
java.lang.RuntimeException: Exception encounted while processing message with ID 4d8fdad4-5a10-46d9-897f-bc055783c38d
at com.amazonaws.services.sqs.util.SQSMessageConsumer.handleMessage(SQSMessageConsumer.java:152)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: Request is throttled. (Service: AmazonSQS; Status Code: 403; Error Code: RequestThrottled; Request ID: 4ab7c2ac-bc73-5a64-8355-948ea21fcffc)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2235)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2202)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2191)
at com.amazonaws.services.sqs.AmazonSQSClient.executeTagQueue(AmazonSQSClient.java:2043)
at com.amazonaws.services.sqs.AmazonSQSClient.tagQueue(AmazonSQSClient.java:2015)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.tagQueue(AbstractAmazonSQSClientWrapper.java:195)
at com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient.lambda$tagQueue$13(AmazonSQSVirtualQueuesClient.java:235)
at java.util.Optional.orElseGet(Optional.java:267)
at com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient.tagQueue(AmazonSQSVirtualQueuesClient.java:235)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.tagQueue(AbstractAmazonSQSClientWrapper.java:195)
at com.amazonaws.services.sqs.AbstractAmazonSQS.tagQueue(AbstractAmazonSQS.java:223)
at com.amazonaws.services.sqs.SQSExecutorService$Metadata.saveToTag(SQSExecutorService.java:159)
at com.amazonaws.services.sqs.SQSExecutorService$SQSFutureTask.send(SQSExecutorService.java:325)
at com.amazonaws.services.sqs.SQSScheduledExecutorService$ScheduledSQSFutureTask.run(SQSScheduledExecutorService.java:152)
at com.amazonaws.services.sqs.SQSExecutorService.accept(SQSExecutorService.java:196)
at com.amazonaws.services.sqs.util.SQSMessageConsumer.accept(SQSMessageConsumer.java:166)
at com.amazonaws.services.sqs.util.SQSMessageConsumer.handleMessage(SQSMessageConsumer.java:145)
... 10 more

Oct 17, 2019 7:45:48 AM com.amazonaws.services.sqs.AmazonSQSIdleQueueDeletingClient checkQueuesForIdleness
INFO: Checking all queues begining with prefix __tmpQueue__ for idleness
Oct 17, 2019 7:45:49 AM com.amazonaws.services.sqs.util.SQSQueueUtils lambda$static$0
SEVERE: Unexpected exception
java.lang.RuntimeException: Encounted error when checking queues for idleness (prefix = __tmpQueue__)
at com.amazonaws.services.sqs.IdleQueueSweeper.checkQueuesForIdleness(IdleQueueSweeper.java:61)
at com.amazonaws.services.sqs.IdleQueueSweeper.lambda$new$f73a843a$1(IdleQueueSweeper.java:46)
at com.amazonaws.services.sqs.executors.DeduplicatedRunnable.run(DeduplicatedRunnable.java:29)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at com.amazonaws.services.sqs.SQSScheduledExecutorService$ScheduledSQSFutureTask.access$201(SQSScheduledExecutorService.java:33)
at com.amazonaws.services.sqs.SQSScheduledExecutorService$ScheduledSQSFutureTask.run(SQSScheduledExecutorService.java:150)
at com.amazonaws.services.sqs.SQSExecutorService.accept(SQSExecutorService.java:196)
at com.amazonaws.services.sqs.util.SQSMessageConsumer.accept(SQSMessageConsumer.java:166)
at com.amazonaws.services.sqs.util.SQSMessageConsumer.handleMessage(SQSMessageConsumer.java:145)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: 948de23d-36c1-5401-88d1-b41f28adb291)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2235)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2202)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2191)
at com.amazonaws.services.sqs.AmazonSQSClient.executeListQueues(AmazonSQSClient.java:1404)
at com.amazonaws.services.sqs.AmazonSQSClient.listQueues(AmazonSQSClient.java:1376)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.listQueues(AbstractAmazonSQSClientWrapper.java:135)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.listQueues(AbstractAmazonSQSClientWrapper.java:135)
at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.listQueues(AbstractAmazonSQSClientWrapper.java:135)
at com.amazonaws.services.sqs.AbstractAmazonSQS.listQueues(AbstractAmazonSQS.java:158)
at com.amazonaws.services.sqs.IdleQueueSweeper.lambda$checkQueuesForIdleness$7dce85cd$1(IdleQueueSweeper.java:54)
at com.amazonaws.services.sqs.util.SQSQueueUtils.forEachQueue(SQSQueueUtils.java:153)
at com.amazonaws.services.sqs.IdleQueueSweeper.checkQueuesForIdleness(IdleQueueSweeper.java:54)
... 19 more`

Regards
Hans Christian

**Comment by robin-aws** [comment] 2019-11-01 16:22
Thanks for the information. I'll definitely leave this issue open since the library should handle this case better, but can I assume that you are at least unblocked for now?

**Comment by hcalsos** [comment] 2019-11-04 08:12
Thanks for the feedback. We are unblocked now, but we had to set the IdleQueueSweepingPeriod to 0 for our testing account, thats seems to solve the issue with throttling.

**Comment by saurabhmbm** [comment] 2020-05-11 14:23
Hi,

Facing same issue of "Request is throttled" and setting IdleQueueSweepingPeriod = 0 is not working either...

Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: Request is throttled. (Service: AmazonSQS; Status Code: 403; Error Code: RequestThrottled; Request ID: 798ffc63-8afa-5f06-a18e-ab50eaa28b58)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524) ~[aws-java-sdk-core-1.11.721.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2207) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2174) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2163) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.executeListQueueTags(AmazonSQSClient.java:1329) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.listQueueTags(AmazonSQSClient.java:1301) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.listQueueTags(AbstractAmazonSQSClientWrapper.java:141) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient.lambda$listQueueTags$17(AmazonSQSVirtualQueuesClient.java:249) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
	at com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient.listQueueTags(AmazonSQSVirtualQueuesClient.java:249) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.util.AbstractAmazonSQSClientWrapper.listQueueTags(AbstractAmazonSQSClientWrapper.java:141) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.AbstractAmazonSQS.listQueueTags(AbstractAmazonSQS.java:143) ~[aws-java-sdk-sqs-1.11.721.jar:na]
	at com.amazonaws.services.sqs.SQSExecutorService$SQSFutureTask.getMetadataFromTags(SQSExecutorService.java:289) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.SQSExecutorService$SQSFutureTask.send(SQSExecutorService.java:295) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.SQSExecutorService.execute(SQSExecutorService.java:94) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.SQSScheduledExecutorService.execute(SQSScheduledExecutorService.java:19) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
	at com.amazonaws.services.sqs.executors.ExecutorUtils.lambda$acceptOn$2(ExecutorUtils.java:69) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at com.amazonaws.services.sqs.util.SQSQueueUtils.forEachQueue(SQSQueueUtils.java:164) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	at com.amazonaws.services.sqs.IdleQueueSweeper.checkQueuesForIdleness(IdleQueueSweeper.java:54) ~[amazon-sqs-java-temporary-queues-client-1.0.2.jar:na]
	... 19 common frames omitted

**Comment by adam-aws** [comment] 2020-07-28 16:12
Reopening to investigate "Request is throttled"  issues

**Comment by adam-aws** [comment] 2020-08-28 16:01
Closing this since increasing the sweeping period  and heartbeating can help prevent throttling issues

**Closed by adam-aws** 2020-08-28 16:01 UTC
