### ISSUE TITLE
delay and period shall be kept in nano second

### ISSUE THREAD

**Issue by ninahma** [awslabs/amazon-sqs-java-temporary-queues-client#28] opened 2020-01-14 16:37 UTC
https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/blob/87266b9a908d9b6fb80f398b37c8085c41a529d8/src/main/java/com/amazonaws/services/sqs/SQSScheduledExecutorService.java#L64

Hi,
It looks like there is an invalid initialization of period and delay parameters in the following constructor of ScheduledSQSFutureTask:
After this.delay and this.period is set, the later code shall use this.delay and this.period. 

            this.delay = unit.toNanos(delay);
            this.period = unit.toNanos(period);

            messageContent.setMessageAttributesEntry(DELAY_NANOS_ATTRIBUTE_NAME, 
                    longMessageAttributeValue(**delay**));
            messageContent.setMessageAttributesEntry(PERIOD_NANOS_ATTRIBUTE_NAME, 
                    longMessageAttributeValue(**period**));

            this.time = getTime(**delay**);

 It looks it shall be 

            this.delay = unit.toNanos(delay);
            this.period = unit.toNanos(period);

            messageContent.setMessageAttributesEntry(DELAY_NANOS_ATTRIBUTE_NAME, 
                    longMessageAttributeValue(**this.delay**));
            messageContent.setMessageAttributesEntry(PERIOD_NANOS_ATTRIBUTE_NAME, 
                    longMessageAttributeValue(**this.period**));

            this.time = getTime(**this.delay**);

Otherwise, the default of 5 minutes delay doesn't work and there is an infinite loop sending messages to check for Idle queues.

**Comment by robin-aws** [comment] 2020-01-21 00:14
Thanks for reporting this. I'll find some time later this week to definitively reproduce the issue - I agree that it seems like there's a bug here, and I'd like to understand why my own integration testing worked despite this.

**Comment by sashokbg** [comment] 2020-02-19 10:17
Having the same problem. I have opened an issue too #33 

Is there a release coming soon for this ?
Thank you for your help and time

**Comment by sashokbg** [comment] 2020-02-21 09:23
Hello @robin-aws, I was experiencing the same problem and I have checked out your branch and tested it locally but the problem persists.

**Comment by robin-aws** [comment] 2020-02-26 23:38
Hi @sashokbg - can you provide a bit more detail about the problem you're still observing? By design, the client will send messages through the shared sweeping queue in order to check for orphaned queues to delete. This issue causes that to happen far more often than intended by configuration, so even after this fix you should still see the messages, just less often.

We might want to focus the investigation in #33 if it turns out to not be a simple duplicate of this one. In the meantime I'm prioritizing getting #32 merged and a new version released.

**Comment by sashokbg** [comment] 2020-02-27 16:20
@robin-aws unfortunately our team has decided to abandon the library due to the instability issues. We went on creating a simple two-way communication and manually creating / deleting SQS queues.

I will try to take a look during my free time

**Comment by robin-aws** [comment] 2020-06-16 17:53
Reopening this issue for tracking, since the PR is merged but not yet released.

**Closed** 2020-07-09 18:12 UTC
